### ISSUE TITLE
text is not a valid field for table-crud

### ISSUE THREAD

**Issue by innominata** [YABhq/Laracogs#10]
$ php artisan laracogs:table-crud customers --bootstrap

**  [Exception]
  text is not in the array of valid column types: increments, integer, string, datetime, date, float, binary, blob, boolean, datetimetz, time, decimal, bi
  gint, smallint, tinyint **

**Comment by mlantz** [comment]
Damn must have missed that - will fix tonight - push fixes in a couple hours - thanks

**Comment by innominata** [comment]
adding to the arrays at the start of FormMaker.php and Crud.php 'seemed' to fix it :)

**Comment by mlantz** [comment]
yeah thats what I was going to do - but I'll make it customizable by putting it in the config :)

**Comment by innominata** [comment]
loving it so far :) only other thing is that table-crud is forcing table names in generated files (repository, views) to lowercase, which is fine if your table names are lowercase, but I suck and they arent. :P

**Comment by mlantz** [comment]
Corrected in 1.9.12
