### ISSUE TITLE
Billing database error

### ISSUE THREAD

**Issue by zakkyzebra** [YABhq/Laracogs#100]
Just setup Billing per the docs and when clicking on the Billing link in the navigation it is returning the following error:

QueryException in Connection.php line 769:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'subscriptions.user_meta_id' in 'where clause' (SQL: select * from `subscriptions` where `subscriptions`.`user_meta_id` = 1 and `subscriptions`.`user_meta_id` is not null order by `created_at` desc)

**Comment by mlantz** [comment]
Hey it looks like the column wasnt updated in the subscriptions table - I'll update that today. In your case just update the migration so that it has a `user_meta_id` column instead of `user_id` and it should work fine.
