### ISSUE TITLE
CRUD Creator search misses search-query on paged results

### ISSUE THREAD

**Issue by studiovlijmscherp** [YABhq/Laracogs#101]
When using the CRUD builder to create models + views, the search service is missing the search-param on paged results.

default generated code:
```
public function search(Request $request)
{
  $members = $this->service->search($request->search);
  return view('members.index')->with('members', $members);
}
```

should be:

```
public function search(Request $request)
{
  $members = $this->service->search($request->search)->appends(['search' => $request->search]);
  return view('members.index')->with('members', $members);
}
```

**Comment by mlantz** [comment]
Good call but I think its better suited on the Service layer. I'll add it to the default templates. Anything issues CrudMaker related can be posted [here](https://github.com/yabhq/crudmaker)
