### ISSUE TITLE
Error after fresh starter kits installation

### ISSUE THREAD

**Issue by amirulfirdaus** [YABhq/Laracogs#102]
I got this error after tried to login with admin@admin.com:admin.

> ReflectionException in Container.php line 749:
Class active does not exist

**Comment by mlantz** [comment]
Did you add this line?

`'active' => \App\Http\Middleware\Active::class,`

to your Kernel?

**Comment by amirulfirdaus** [comment]
Nice one, it solved the problem. I didn't include that line in Kernel.php.
