### ISSUE TITLE
API Kit - Do we really want JWT to handle the API authentication ?

### ISSUE THREAD

**Issue by happy-dev** [YABhq/Laracogs#104]
Hi Guys, 

Thanks for this great plugin. First time I am using it and I am impressed by your work. I find it very helpful, it makes me save quite some time. Kuddos ! 

I see you are using JWT to handle the API authentication. 
I am not sure if this is a good idea. 

[According to this opinioated post it is not](http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/), but I would like your opinion if you have one, so I can make the right choice for my own API. 

I would be willing to code an API Kit with session cookies if you guys think this might be a good idea.

Let me know ;)

**Comment by mlantz** [comment]
The API kit using the JWT approach is something we have used in the past on projects that are solely an API for Laravel, while using Ember for the SPA (Ember has a really nice Simple-Auth package). It's proven to be a very handy way to handle those apps, especially with multiple clients on a single API source. In terms of a session cookie API Kit I'd be more than happy to take a look at one. I'd also like to make a Kit that can handle 'token' access for API calls that are not session based.

**Comment by mlantz** [comment]
Message me on Larachat if you'd like to talk details :)
