### ISSUE TITLE
Layout not good after fresh install

### ISSUE THREAD

**Issue by wymedia** [YABhq/Laracogs#108]
I have installed Laracogs starter and then applied Bootstrap to it. The layout does not seem to work well. How can this be fixed? This happens in both Chrome as well as Firefox.

![image](https://cloud.githubusercontent.com/assets/8831818/21074391/e7dc0f4c-bef7-11e6-9681-48123b7aba53.png)

**Comment by mlantz** [comment]
Did you run npm install and gulp?

**Comment by wymedia** [comment]
Thanks. Could it be this is not mentioned in the [doc](https://laracogs.com/docs/kits/bootstrap/) explicitly?
Anyway, trying to run that, the npm install gives me these errors

```
vagrant@homestead:~/Laravel/Youtube$ npm install
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
```

Any idea what it could be?

**Comment by DanJFletcher** [comment]
@wymedia Are you using homestead on Windows?
