### ISSUE TITLE
Laravel 5.4 | Form inputs

### ISSUE THREAD

**Issue by Rav23** [YABhq/Laracogs#110]
Hi there guys,

Firstly I want to congratulate the team on an awesome package. I know L5.4 will only be out in January but is there a way to use laracogs with L5.4 as of this moment? 

I was also wondering how to add new form input types such as datepicker, select2, etc...

**Comment by mlantz** [comment]
Thanks @Rav23 
I have yet to test it with L5.4 but I don't see any reason for it to not work. There would be some oddball stuff with the new route chain methods but that shouldn't be too hard to switch around. 
You can add new form input types in the config `form-maker`.

**Comment by Rav23** [comment]
I just found out that I can't use it with L5.4 yet due to Laracogs having illuminate 5.3 as a dependency. I wonder how others live on the bleeding edge though...

**Comment by mlantz** [comment]
It's just a matter of me adding in dual support for Laracogs, but I have preferred to keep Laracogs supporting the latest 'official' versions of Laravel only. Trying to maintain backwards compatibility is too much.

**Comment by Rav23** [comment]
I understand and appreciate your efforts. I'm learning Laracogs and love it thus far. Hopefully I get to build something cool with it once I'm comfortable. 

Thank YOU once again
