### ISSUE TITLE
Class active does not exist

### ISSUE THREAD

**Issue by ashish64** [YABhq/Laracogs#114]
Laravel version: 5.3
php Version: 5.6
Laracogs version : 2

Laracogs installed as described. After that, i have set up **Application Starter Kit** as explained in documentation. After that, when i try to login, it takes me to  /dasbhoard with following message
**ReflectionException in Container.php line 749: 
Class active does not exist**

Same message when i try to create new controller for dashboard as well. 
Please Help. Im kinda noob at this.

Ashish

**Comment by mlantz** [comment]
No worries @ashish64 can you confirm that you followed these instructions: https://github.com/YABhq/Laracogs#starter

Next did you remove this like regarding the email activation in the docs: `'active' => \App\Http\Middleware\Active::class,` 

If so then you need to remove the 'active' middleware statement in the routes files. Looks like I should add that to the docs

**Comment by ashish64** [comment]
that did the job!! it was quite easy,
as explained in documentation, i didnt wanted users to activate their accounts via email links as im just playing around.. so i had that line commented. You should definitely add that in documentation.

Again, thanks for this quick response!!

**Comment by ramjamx** [comment]
I'm Sorry to re activate this topic but I'm a little lost in this part of the documentation:

```
You can disable it by removing the active middleware from the web routes.
```
Do I need to comment this line in '/app/http/kernel.php': 'active' => \App\Http\Middleware\Active::class,

or I should comment the whole section  Route::group(['middleware' => ['auth', 'active']], function () 
in /routes/web.php

I just need to play around with laracogs without the email token confirmation.

Thank you!

**Comment by mlantz** [comment]
Switch this: `Route::group(['middleware' => ['auth', 'active']]` to this: `Route::group(['middleware' => ['auth']]` and it should bypass the whole activation middleware

**Comment by ramjamx** [comment]
Great! 
Thank you mlantz!
