### ISSUE TITLE
Feature Request: UI based Public Registration Disable

### ISSUE THREAD

**Issue by ashish64** [YABhq/Laracogs#119]
Hello @mlantz 
Its me again
This is sort of a feature request.
It would be pretty awesome if you manage to add "Disable user public registration" button somewhere in admin panel.

And also, can you please let me know exactly how i can perform manual user verification instead of doing email verification.

Lastly, Thank you for spending you precious time in making this all possible and putting it out for everyone to use. You are indeed the real MVP!!

**Comment by mlantz** [comment]
Thank you very much. Hmm, you've given me an idea....

**Comment by mlantz** [comment]
Hey @ashish64 I'm going to close this, but I'll keep you posted on a new package I'm working on

**Comment by ashish64** [comment]
No Worries, @mlantz Im looking forward to it!

**Comment by mlantz** [comment]
Released the kit for this today :)
