### ISSUE TITLE
Layout mixed up

### ISSUE THREAD

**Issue by wymedia** [YABhq/Laracogs#120]
New install. I have run all the steps as indicated in this readme file. However, I always end up with the below UI. Seems the layout is mixed up. Have tried quite a few times, always same result.

Any idea how to fix this?

![image](https://cloud.githubusercontent.com/assets/8831818/22442148/96678efa-e73a-11e6-9ce7-ca5109782d21.png)

**Comment by ashish64** [comment]
I wanted to use my own layout so i never ran artisan command for UI. I just updated the given barebone html with my layout which works perfectly. 
Perhaps you should do that, i find it quicker that way.

Ashish

**Comment by mlantz** [comment]
Sorry @wymedia you tried running things with gulp for 5.3 or webpack for 5.4 `npm run dev`? After doing an npm install?
