### ISSUE TITLE
Heads up! Getting Syntax error or access violation on fresh L5.4.3 Installation

### ISSUE THREAD

**Issue by ashish64** [YABhq/Laracogs#122]
Below are the details:
Tried setting up Laracogs with L5.4.3, everything went smoothly until i ran `php artisan migrate --seed` after
`php artisan laracogs:starter`.  Im looking for the solution at the moment, if someone has come up with something, Please update here!
`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))`

**Comment by mlantz** [comment]
https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by ashish64** [comment]
i just realised i can also solve this by updating 
`'charset' => 'utf8mb4',`
`'collation' => 'utf8mb4_unicode_ci',`
in config/app/database.php to the following
`'charset' => 'utf8',`
`'collation' => 'utf8_unicode_ci',`
depending on the type of app one wishes to make.
