### ISSUE TITLE
Add parameter to disable namespacing mutli_word models in crudmaker

### ISSUE THREAD

**Issue by tmaly1980** [YABhq/Laracogs#123]
Not all snake case model names with multiple words, such as "deal_photos" or "school_buses", are necessarily part of a relationship to another table, so it would be nice to not have crudmaker create namespaced subfolders. If I were to use DealPhoto or SchoolBus as a StudlyCase naming, the subfolders aren't created but the variable names, view folder, etc aren't underscored, ie "dealphotos", "schoolbuses", etc which make it less readable. It would be nice to underscore from studly case as well.

**Comment by mlantz** [comment]
I believe this will solve the problem: https://github.com/YABhq/CrudMaker/pull/31

@Braunson provided a solution
