### ISSUE TITLE
Different redirect route according to permission

### ISSUE THREAD

**Issue by ashish64** [YABhq/Laracogs#128]
Hello,

How do i make Admin and Normal users redirect to different controllers after login.
Like if logged in user is admin go to
`Route::get('/dashboard', 'DashboardController@admin');`
if logged in user is normal user
`Route::get('/dashboard', 'DashboardController@normal');`

Thanks

**Comment by mlantz** [comment]
I've done it a couple different ways, the most recent way was a DashboardController@director which redirected them to either location, or you could have everything point to normal but if you're an admin get a redirect to the admin, or everything point to admin and redirect the normals

**Comment by ashish64** [comment]
I actually did it this way, if there is simpler way or im doing something very stupid, let me know.
in my route will point to DashboardController@index and in the index following
```
if(Gate::allows('admin'))
        {
           $this->showSuperuserstuff();
        }
        else
        {
             $this->showSupernormalstuff();
        }
```
Let me know.

**Comment by mlantz** [comment]
Yup I've done it that way before too :) I don't really know an official 'BEST' way

**Comment by amirulfirdaus** [comment]
The way I've done it by using AuthenticatesUsers trait.
```
\App\Http\Controllers\Auth\LoginController.php
```
Add this method to that controller:
```
    /**
     * Check user's role and redirect user based on their role
     * @return 
     */
    public function authenticated()
    {
        if(auth()->user()->hasRole('admin'))
        {
            return redirect('/admin/dashboard');
        } else {
            return redirect('/user/dashboard');
        }
    }
```

**Comment by mlantz** [comment]
Hey @amirulfirdaus put in a PR I like that
