### ISSUE TITLE
unable to generate user_meta when inviting

### ISSUE THREAD

**Issue by ashish64** [YABhq/Laracogs#130]
Hello, can you advise me with this.
Whenever i try to invite user as team member, it generates the user but doesnt generate user_meta.
it gives me the following message
```
Exception in UserService.php line 184: 
We were unable to generate your profile, please try again later.
```

Ashish

**Comment by mlantz** [comment]
Did you set your mail_driver to log in your dev env? if your mail settings are not done it will fail to complete the setup

**Comment by ashish64** [comment]
here is my mail driver section
```
MAIL_DRIVER=log
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

```

Same thing with user registration as well
```
Exception in UserService.php line 184: 
We were unable to generate your profile, please try again later.
```

**Comment by mlantz** [comment]
Just go into the user service and dd the error message. It will point you in the right direction.

**Comment by ashish64** [comment]
@mlantz 
Thanks for this man.
Conversation with you always teaches me new things.
What actually happened was i had added few fields in the user_meta and they were not set to 'NULL' so they could accept empty records. 

Thanks alot.

**Comment by mlantz** [comment]
:) no problem happy to help

**Comment by ashish64** [comment]
hay, @mlantz 
Now im getting another exception when i invite user, from the `UserController@getInvite`
```
HttpException in Handler.php line 133: 
This action is unauthorized.
```

**Comment by mlantz** [comment]
It's likely an admin action but you're trying to do it with a 'member' level account, review the routes you'll see the permission statements in there

**Comment by ashish64** [comment]
This is my route for this specific action.
```
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
        Route::get('users/invite', 'UserController@getInvite');
        Route::post('users/invite', 'UserController@postInvite');
}
```
Below is my screenshot of my role_user table
![git](https://cloud.githubusercontent.com/assets/312075/23508464/ebc88cda-ff79-11e6-8358-ecc470d5f804.png)

not sure what am i missing :(

**Comment by mlantz** [comment]
Hmmm, I'm not too sure take a look at the log and see if you can find something that would be blocking it, try disabling the middleware temporarily if need be

**Comment by mlantz** [comment]
Were you able to figure out what was wrong?
