### ISSUE TITLE
BUG: Inviting users as admin (not to team) throw's error

### ISSUE THREAD

**Issue by cesasol** [YABhq/Laracogs#135]
Using the starter kit, when adding users from /admin/users/invite, throws `This action is unauthorized.`
I think it may be related to the changes made on #105
I'm new to laravel, so I don't think that I can fix this issue myself

**Comment by mlantz** [comment]
It's not a bug, technically, you can change all the code that you're talking about. The intent with the starter kit is that it gives you pre-written code that you can customize to your liking. Feel free to remove the thrown error, or change up the roles and permissions to enable other users to add people to teams.
