### ISSUE TITLE
Route [login] not defined.

### ISSUE THREAD

**Issue by cjrigdon** [YABhq/Laracogs#137]
I have installed both Quarx and the Laracogs starter kit.  When I try to navigate to the dashboard or any of the Quarx routes, I would expect to be prompted to login, but instead I get the following error.  I can see all of the routes that were generated in the web.php when I ran the Laracogs install, so not sure why this error.

![screen shot 2017-04-02 at 9 06 48 am](https://cloud.githubusercontent.com/assets/9053151/24588381/1ef7aa56-1784-11e7-8043-fda208b8898f.png)

**Comment by cjrigdon** [comment]
I was able to fix this by adding a name to the login route.

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

I left this open because I am not sure if maybe the install is for an older version of Laravel (I am using 5.4).  If so, is there anything else I need to do?

**Comment by mlantz** [comment]
Looks like the framework updated the signatures. I'll push an update to Laracogs to fix this but that only helps on new installs.  Looks like you'll want to add this to the registration route as well:

Should now look like:

```
/*
|--------------------------------------------------------------------------
| Login/ Logout/ Password
|--------------------------------------------------------------------------
*/
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Registration & Activation
|--------------------------------------------------------------------------
*/
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
```
