### ISSUE TITLE
Class User\BillingController does not exist

### ISSUE THREAD

**Issue by FrankWiebe** [YABhq/Laracogs#138]
Installed Laravel Cashier and than installed the billing kit, but I get this issue 
Class User\BillingController does not exist

**Comment by mlantz** [comment]
Can you check if the file exists and then show me the RouteServiceProvider?

**Comment by FrankWiebe** [comment]
I made sure it exists.
Here's the RouteServiceProvider
`<?php

namespace App\Providers;

use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

class RouteServiceProvider extends ServiceProvider
{
    protected $namespace = 'App\Http\Controllers';

    public function boot()
    {
        parent::boot();
    }

    public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();
    }

    protected function mapWebRoutes()
    {
        Route::middleware('web')
             ->namespace($this->namespace)
             ->group(base_path('routes/web.php'));
        require base_path('routes/billing.php');
    }

    protected function mapApiRoutes()
    {
        Route::prefix('api')
             ->middleware('api')
             ->namespace($this->namespace)
             ->group(base_path('routes/api.php'));
    }
}
`

**Comment by mlantz** [comment]
This is not proper:

```
         ->group(base_path('routes/web.php'));
    require base_path('routes/billing.php');
```

The docs mention that it should look like:

```
->group(function () {
    require base_path('routes/web.php');
    require base_path('routes/billing.php');
});
```

Should work like a charm then :)

**Comment by mlantz** [comment]
Sorry, it looks like its in the console commands comments but not in the readme properly. I'm updating today, sorry for delays.
