### ISSUE TITLE
HttpException in Handler.php line 133: This action is unauthorized.

### ISSUE THREAD

**Issue by marcwitteveen** [YABhq/Laracogs#139]
When assigning a new user as an administrator I receive the following message:
HttpException in Handler.php line 133: This action is unauthorized.

The laracogs / laravel installation is the default, no changes were made except for the ones instructed on the laracogs website.

I've doubled checked the administrator's access level and it is set correct. The email service used is from mailtrap.io.

Strangely enough, the log file does not show any information, even though debugging is enabled.

**Comment by mlantz** [comment]
Look at the `UserInviteRequest` its likely that its checking for a team-admin vs an admin. I'm putting together a fix for this sorry.
