### ISSUE TITLE
Dashboard page now showing after user logs in

### ISSUE THREAD

**Issue by marcwitteveen** [YABhq/Laracogs#140]
When a user is authenticated the user is redirected to /user/dashboard, however, the page that is displayed is the 404 page (Where am I?). 

When I change the url to /dashboard the expected page shows fine.

I would think that the function authenticated in LoginController.php needs to be changed.

`
public function authenticated()
    {
        if(auth()->user()->hasRole('admin'))
        {
            return redirect('/dashboard');
        } else {
            return redirect('/user/dashboard');
        }
    }
`

**Comment by mlantz** [comment]
Thanks for catching that I forgot to update it, the plan was to add a separate dashboard for admins, but, it was suggested by a PR a while ago but I never did finish updating it. Expect an update in a day or so.
