### ISSUE TITLE
Activity middle ware unable to find activity helper

### ISSUE THREAD

**Issue by jayjfletcher** [YABhq/Laracogs#145]
when I add activity to a route as middleware, an error is thrown because the helper can not be found

**Comment by mlantz** [comment]
I assume this was fixed with the file name blunder on my part?

**Comment by jayjfletcher** [comment]
Unfortunately no.

But I did find that the helpers aren't working because they aren't global.
They're being defined within the service provider boot function and this is assigning the namespace to the function.

```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;

class ActivityServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     */
    public function boot()
    {
        if (function_exists('activity')) {
            function activity($description)
            {
                return Activity::log($description);
            }
        }
    }
```

So to call activity() you would have to use App\Providers\activity()

To make the functions global they would have to be moved to an external helpers file, outside the current namespace, and then included.

Also I noticed the helpers are being defined only if the function already exists. It should be if it does NOT exists.

```
if (function_exists('activity')) {
            function activity($description)
            {
                return Activity::log($description);
            }
}

change to ->

if (!function_exists('activity')) {
            function activity($description)
            {
                return Activity::log($description);
            }
}
```

Also the activity kit isn't the only place helpers are being defined this way.

**Comment by mlantz** [comment]
Wow thats an oversight sorry about that. I'll push a fix today

**Comment by jayjfletcher** [comment]
This issue is also present in the feature kit

**Comment by mlantz** [comment]
Awesome, fix on the way!
