### ISSUE TITLE
[QUESTION] How to use 'sectioned' config

### ISSUE THREAD

**Issue by Shandur** [YABhq/Laracogs#148]
Hello. I'm developing a project using modular approach. In project root I have Modules/ folder which contains User/ and Company/ folders (modules). I want to generate crud code for them using your 'crudmaker' generator. In crudmaker.php config I found 'sectioned' config. As I understood it generates code in provided _section_ .
So, the question is how I can use it? Because I didn't find any docs about it. Perhaps, I need to pass some parameter for console command 'crudmaker' or something else.
Thanks!

p.s. Thank you for the great project! It's really awesome!

**Comment by mlantz** [comment]
`crudmaker:new user_company` should split it into User/Company if not let me know and thanks, we're delighted to keep working on it.

**Comment by Shandur** [comment]
@mlantz Thank you for reply! Don't you plan to create commands that generate boilerplate code like one module? For instance, crudmaker:new user --module . And place in config the root folder for all modules. Because your project is more suited for middle-big projects and placing all the code in app/ folder could be pretty messy.
It's just question and suggestion :)
Thanks!

**Comment by mlantz** [comment]
Thats a tough call. I could add a method for generating a CRUD as a package which could be loaded via a provider file similar to how I'm doing modules in Quarx. Thanks for the suggestion.

**Comment by Shandur** [comment]
@mlantz I'd be really great! I hope you'll make it!
If you need any help, I'll be glad to help you with :)
Also, can suggest looking at this [package](https://nwidart.com/laravel-modules/v1/introduction) as example (not advert).
Cheers!

**Comment by mlantz** [comment]
Its funny you say that - I had some time last night and was in a good state so I put together last night - I have a couple tests to write still but it should be ready by Monday I think
