### ISSUE TITLE
Use @example.org for the default admin login RFC 2606

### ISSUE THREAD

**Issue by CoolGoose** [YABhq/Laracogs#149]
Hello there.

Since admin.com isn't a reserved url (seems registered by Amazon in 94) i think it would be best to switch to one of the reserved top level url's according to [RFC 2606](https://tools.ietf.org/html/rfc2606) in order to not spam that email address with registrations.

I can make a pull request if you're ok with the change :) 

```
example.com
example.net
example.org
```

**Comment by mlantz** [comment]
yeah sure

**Comment by CoolGoose** [comment]
@mlantz https://github.com/YABhq/Laracogs/pull/150

**Comment by CoolGoose** [comment]
Merge is up 👍 
My question now is, how can one update the site docs ? :)

**Comment by mlantz** [comment]
Working on it and releasing to day ;)
