### ISSUE TITLE
Typo in artisan laracogs:starter

### ISSUE THREAD

**Issue by timothyallan** [YABhq/Laracogs#15]
Guys, this repo is bananas, great work. One small thing so far, at the end of running laracogs:starter it says:
```
Don't forget to run:
composer dump
Then:
artisan migration
```

It should be `artisan migrate`

**Comment by mlantz** [comment]
I totally missed that - thank you! and great catch

**Comment by timothyallan** [comment]
No problem... oh, and while I'm QA'ing for you:

In `https://github.com/YABhq/Laracogs/blob/develop/README.md`

where it says 
```
For Laravel 5.2

You will also need to set the location of the email for password reminders. (app/auth.php - at the bottom)
```

the file location should read 

`config/auth.php`

;)

**Comment by mlantz** [comment]
These will be in the next release
