### ISSUE TITLE
Do not overwrite Model if it already exists.

### ISSUE THREAD

**Issue by vpakg** [YABhq/Laracogs#151]
### Preliminary information

+ **Laravel Version** : 5.4.23
+ **Laracogs Version**: ^2.2

For illustrative purposes, I'll use "Car" as the CRUD model that I need to create.

### Description of Action

Ran `php artisan crudmaker:new Car`.  

### Description of Error

The model Car already existed, had all the proper traits and relationships set up. The model was replaced by a blank Model with a few boilerplate options.

### Expected Result

The application should first check if the Model exists, if it does, it should not overwrite it with boilerplate content.

**Comment by mlantz** [comment]
Good call - I've made updates to prevent overwriting of files - will push updates today

**Comment by vpakg** [comment]
@mlantz Awesome! I'll close the issue.
Great work.
