### ISSUE TITLE
CRUD Integration test

### ISSUE THREAD

**Issue by bderubinat** [YABhq/Laracogs#152]
Hi,
I'm trying to figure out the built in oh-unit tests. As I'm new to using oh-unit, I wonder whether I just dd not get it or I found a bug.

This is what I find in the integration test folder:
```
class AreaServiceIntegrationTest extends TestCase
// snip
    public function testUpdate()
    {
        // create the item
        $item = $this->service->create($this->originalArray);

        $response = $this->service->update($item->id, $this->editedArray);

        $this->assertEquals(1, $response->id);
        $this->seeInDatabase('layout_areas', $this->editedArray);
    }

```

Which fails on  `$this->assertEquals(1, $response->id);` with error:
```
1) AreaServiceIntegrationTest::testDestroy
Failed asserting that 1 is true.

.../tests/integration/AreaServiceIntegrationTest.php:99
```

Looking at Model class, seems that update method returns a bool and it is therefore not expected to find ->id on the retired bool.
```
    /** \Illuminate\Database\Eloquent\Model
     * Update the model in the database.
     * <snip>
     * @return bool
     */
    public function update(array $attributes = [], array $options = [])
    {
        if (! $this->exists) {
            return false;
        }

        return $this->fill($attributes)->save($options);
    }

```

I would replace
 $this->assertEquals(1, $response->id);
with 
 $this->assertEquals(true, $response);

correct?

Bernard

PS: BTW, seeInDatabase changed to assertDatabaseHas in larval 5.4

**Comment by mlantz** [comment]
Thanks for the reminder about `assertDatabaseHas` but your test would be more accurate if the assertion was `$this->assertEquals($item->id, $response->id);` There is no guarantee that the `create` method called at the beginning of the test will have an $item of 1.

**Comment by bderubinat** [comment]
Thanks Matt,
My point is that `\Illuminate\Database\Eloquent\Model::update` method (which I assume is the one called) does return a `bool`

So, unless I'm wrong on testUpdate calling `update` from `\Illuminate\Database\Eloquent\Model`, there is no point on checking the id, but rather whether update returns true. 

a) I'm new to all this, so not sure I get it right

b) if I get it right, you probably need to update the testUpdate as generated by crudmaker.

**Comment by mlantz** [comment]
The update only returns bool correct - the method got changed in 5.4 so the update returns bool if the update was actually performed if there is no change in the data then the update doesnt do anything.

And yeah I removed the ID checker there the tests generated by the CrudMaker. Thanks. Will push update soon
