### ISSUE TITLE
Model boilerplate comment breaking `$fillable` array.

### ISSUE THREAD

**Issue by vpakg** [YABhq/Laracogs#153]
### Preliminary information

+ **Laravel Version** : 5.4.23
+ **Laracogs Version**: ^2.2

### Description of Action

Ran `php artisan crudmaker:new Profile`.  

### Description of Error

Model boilerplate, closing brackets for `$fillable` is generating the closing brackets inside the comment, which throws an error.

Generated code:

```PHP 
  public $fillable = [
// Profile table data    ];
```

### Expected Result

The comment portion of the code should not affect the closing brackets.

**Comment by vpakg** [comment]
I've submitted a [pull request](https://github.com/YABhq/CrudMaker/pull/36) on the crudmaker's package, just in case:

**Comment by mlantz** [comment]
Oh this would happen in the case of not filling out the schema - doh! - I often test with the schema in place thanks!
