### ISSUE TITLE
Subdomains?

### ISSUE THREAD

**Issue by dambridge** [YABhq/Laracogs#156]
Hi there,
I've abandoned Spark in favour of Laracogs, looks terrific so far! I'm struggling a bit with how to handle a subdomain with the Starter kit right now (i.e. `app.myapp.com`), as the routes break whether or not I put them into a domain group. Would you have any pointers or suggested approach to doing this?

Hope it's ok to ask this here.

**Comment by mlantz** [comment]
Its always ok to ask. I was just testing with domains and it appears to work, do you have homestead and your hosts files updated accordingly? I tested with `Route::group(['domain' => 'app.laracogs.dev'], function () {});` in both the `RouteServiceProvider` and the `routes/web.php` so I'm a little stumped as to why it isn't working.

**Comment by dambridge** [comment]
Hey, thanks and sorry for the delay in responding. I think I had mis-configured the routes between the auth and rest of the app. Seems to be good now. Closing!
