### ISSUE TITLE
[ReflectionException]   Class Api\AuthController does not exist

### ISSUE THREAD

**Issue by timothyallan** [YABhq/Laracogs#16]
I've done the install twice now just to make sure I didn't miss anything. Fresh version of Laravel, with artisan starter and artisan api run, and all the associated changes and updates made.

I can see the properly namespaced Api\AuthController there, and it's included in the RouteServiceProvider via api-routes.php. Tried composer dump/update etc and still no go.

Tried the biling component and get the same issue.. can't find the Billing Controller.

`php artisan route:list` fails as well with the error.

Any suggestions?

**Comment by mlantz** [comment]
Where did you add this line: `require app_path('Http/api-routes.php');`? To the map() or mapWebRoutes() method?

**Comment by timothyallan** [comment]
yes, putting it outside of the closure in mapWebRoutes at 2am will certainly cause that error.

Thanks Matt :)
