### ISSUE TITLE
Offset issue in dashboard.blade.php

### ISSUE THREAD

**Issue by mefenlon** [YABhq/Laracogs#161]
The layout of the dashboard was displaying improperly.
The source of the problem is 
resources/views/dashboard.blade.php
`  <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        @yield('content')
    </div>`

Should be
`<div class="col-sm-9 col-md-10 main">
        @yield('content')
    </div>`

**Comment by alsto** [comment]
Did you run _npm run dev_? Dashboard looked good with the original code after that for me.
