### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by Rav23** [YABhq/Laracogs#162]
Will we get a laravel 5.5 compatible version? Used it on a small project but now I would like to use it on a larger and more serious project.

**Comment by CaddyDz** [comment]
The readme file on this repo says it's compatible with laravel 5.5 but composer requires illuminate/support 5.4.* [Here](https://github.com/YABhq/Laracogs/blob/develop/composer.json#L18)
Any thoughts?

**Comment by CaddyDz** [comment]
This has been fixed on #1b0650f

**Comment by Rav23** [comment]
Thank YOU @CaddyDz
