### ISSUE TITLE
Semantic layout doesn't look good

### ISSUE THREAD

**Issue by jagroop** [YABhq/Laracogs#166]
# Issues :
- Container top padding
- Duplicate Options

![dess](https://user-images.githubusercontent.com/12444128/30198686-97dabc8a-948c-11e7-8663-f8e2c58e9cf8.png)

**Comment by jagroop** [comment]
fixed after reinstalling dependencies

**Comment by CaddyDz** [comment]
Deleting Bootstrap CDN from the master layout makes it look even better
