### ISSUE TITLE
Can't add Features

### ISSUE THREAD

**Issue by GameFanager** [YABhq/Laracogs#168]
After going through the features setup and running `php artisan laracogs:features` the files that the doc says should be published are not getting published resulting in an error when i go to /admin/features

`Class Admin\FeatureController does not exist`

After going through the entire list of files that should be published, the only file that doesn't appear to publish is app/Http/Controllers/Admin/FeatureController.php

**Comment by GameFanager** [comment]
nevermind.

pebcak

**Comment by euperia** [comment]
I don't suppose you could document what the problem was, and how you fixed it?  Got the same problem here.  Class and file does exist, cleaned cache, ran `composer dump` - still no luck.
