### ISSUE TITLE
Typo in startup guide or UsersTableSeeder

### ISSUE THREAD

**Issue by gcpatton** [YABhq/Laracogs#169]
The startup guide lists "admin@example.**org**" as the login e-mail, but the seeder provides
`'email' => 'admin@example.com',`

Just a minor typo either way!

**Comment by CaddyDz** [comment]
Already seen and suggested to be fixed
See https://github.com/YABhq/Laracogs/pull/167

**Comment by gcpatton** [comment]
Sorry for the duplicate! 👍
