### ISSUE TITLE
Api generation has unnecessary documentation

### ISSUE THREAD

**Issue by rntorm** [YABhq/Laracogs#170]
With laravel 5.5.* version following step is unecessary in the API generation process

`Add this line to (app/Providers/RouteServiceProvider.php) in the mapWebRoutes() method:
require base_path('routes/api.php');
`
RouteserviceProvider allready provides method for injecting API routes: 
`
    protected function mapApiRoutes()
    {
        Route::prefix('api')
             ->middleware('api')
             ->namespace($this->namespace)
             ->group(base_path('routes/api.php'));
    }`

**Comment by CaddyDz** [comment]
Laracogs supposedly supports earlier versions of Laravel so it's a better idea to keep the documentation backward compatible

**Comment by mlantz** [comment]
Actually I do believe that was a Typo. I've fixed it in the command documentation. Thanks.
