### ISSUE TITLE
Are the install docs up to date with Laravel 5.5?

### ISSUE THREAD

**Issue by blueshift9** [YABhq/Laracogs#173]
In the install docs, there is a part that says "Update the App\User::class in: 'config/auth.php' and 'database/factory/ModelFactory.php' to this:".
The first file exists, the second does not. Anyone come across this?

**Comment by CaddyDz** [comment]
The file `database/factories/ModelFactory.php` does exist if you ran the laracogs:starter or installed a fresh app using the `Laracogs Installer`.  
As for the docs, it does need some tweaks but I haven't found anything incompatible with _Laravel 5.5_  
[Proof for skeptics](https://github.com/CaddyDz/English/blob/master/database/factories/ModelFactory.php)

**Comment by blueshift9** [comment]
Hhhm, I definitely ran the laracogs:starter command since that's right at that beginning of that page. I will try again to verify when I have a chance.

**Comment by mlantz** [comment]
The latest build should no longer use the `database/factories/ModelFactory.php`. I'll review docs this weekend, the site is currently not up to date but I should be able to deploy this weekend. Thanks.
