### ISSUE TITLE
how can i use datetime in @form_maker_table, its just using date, and cannt using time

### ISSUE THREAD

**Issue by rendyif** [YABhq/Laracogs#174]

**Comment by CaddyDz** [comment]
[RTFM](https://laracogs.com/docs/services/form_maker/#fromarray)

**Comment by rendyif** [comment]
thank you and im sory for being fool

**Comment by mlantz** [comment]
Feel free to post any issues, sometimes the docs need some updates and better descriptions. Thanks @CaddyDz
