### ISSUE TITLE
Crudmaker : Avoid using snake case when generating from table

### ISSUE THREAD

**Issue by Gog0** [YABhq/Laracogs#175]
Hi,

I'm trying to do some CRUD generations from an existing database but I'm facing a problem.

I have a table called "helicopter_types" but I don't want to generate App\Models\Helicopter\Type but App\Models\HelicopterType

And same for controllers/services/etc...

Is there any way to do that?

Thanks

**Comment by mlantz** [comment]
If you use CamelCase it should work fine `App\Services\HelicopterTypeService` etc will be generated and the table base of `helicopter_types`

**Comment by Gog0** [comment]
@mlantz There is a consitency issue on this then because if I use CamelCase with crudmaker:table it's looking for a table with the CamelCased name but actually generation Models/routes/... with snake_case names.

So my workaround for now is to rename the table with camelcase then use the crudmaker:table command, then rename the table back to snake_case

**Comment by mlantz** [comment]
I'll review this to ensure consistency. Thanks.
