### ISSUE TITLE
Suggest updating either the UserTableSeeder or Docs

### ISSUE THREAD

**Issue by whoacowboy** [YABhq/Laracogs#19]
Thanks for such an awesome toolkit!

I'd like to suggest updating the UserTableSeeder file or the Docs to actually add a user with privileges. 

I was getting a few errors when I first installed the cogs and was unclear if it was a installation issue, configuration issue or what. 

```
ErrorException in AuthServiceProvider.php line 30:
Trying to get property of non-object
```

```
ErrorException in InputMaker.php line 199:
Trying to get property of non-object
```

```
ErrorException in InputMaker.php line 199:
Trying to get property of non-object
(View: /home/vagrant/Projects/site/resources/views/user/meta.blade.php)
```

I figured it out pretty quickly but it would be nice if it were mentioned in the docs. It would have saved me some time double checking everything.

I was thinking something like the below addition.
```
<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user = App\Repositories\User\User::create(array(
            'name' => 'Admin',
            'email' => 'admin@example.com',
            'password' => Hash::make('password'),
            'remember_token' => hash_hmac('sha256', str_random(40), env('APP_KEY')),
        ));

        $user->meta()->save(new \App\Repositories\UserMeta\UserMeta(
            [
                'phone' => '415-555-1212',
                'marketing' => 1,
                'terms_and_cond' => 1
            ]
        ));

        $admin_role = \App\Repositories\Role\Role::findByName('Admin');
        $user->roles()->save($admin_role);
    }
}
```

**Comment by mlantz** [comment]
Hmm, I like the idea of the seeder for test purposes - and I need to update the docs but User with ID #1 has the ability to set themselves as an admin by updating their settings. Also in this case I would suggest using the `UserService` and the create method: `create($user, $password, $role = 'member', $sendEmail = true)` but maybe it would be better to have the starter console command have a --withAdmin option that will add an admin to your app?

**Comment by whoacowboy** [comment]
I have literally only been going through this a couple of hours today, so you have a much better idea on exactly where to put it. It would be cool to have a --withAdmin, but I think just updating the Docs would be huge.

**Comment by mlantz** [comment]
Will do, website redesign is also in the works :)

**Comment by whoacowboy** [comment]
awesome, looking forward to it.
