### ISSUE TITLE
meta_blade error

### ISSUE THREAD

**Issue by tpharaoh** [YABhq/Laracogs#21]
on the following pages:
user/settings
/admin/users/3/edit

ErrorException in InputMaker.php line 199:
Trying to get property of non-object (View: ........./resources/views/user/meta.blade.php) (View: ............../resources/views/user/meta.blade.php)

**Comment by mlantz** [comment]
My suspicion is that it has to do with the role.

**Comment by mlantz** [comment]
Yup there was a missing part for the bootstrap views which sets value of the roles relationship - thanks for catching that
