### ISSUE TITLE
Addition of Max Nesting Solution to Docs:

### ISSUE THREAD

**Issue by emforce** [YABhq/Laracogs#26]
I faced this issue initially when setting up Laracogs, turned out to be an issue with xdebug.max_nesting_level configuration. 

This is solved by adding 

`ini_set('xdebug.max_nesting_level', 500);`

to bootstrap > autoload.php

**Comment by mlantz** [comment]
Added an FAQ to the docs site with this point about xdebug as the first point. Thanks.
