### ISSUE TITLE
Default Dashboard View

### ISSUE THREAD

**Issue by Mezzair** [YABhq/Laracogs#27]
When using the starter kit, the default dashboard view loads the main layout file and not the 'dashboard.main' blade layout that gets generated.

**Comment by fishmad** [comment]
I just ran a fresh laravel 5.1 and laracogs starter kit installation, go to dashboard and see this:

**Dashboard!**
- Settings
- Teams
- Logout

Team page has error other pages working ok:

```
Whoops, looks like something went wrong.

1/1
FatalErrorException in ce4cfde0083ac30d67601c2891ce82b1 line 32:
syntax error, unexpected '$team' (T_VARIABLE)
```

**Comment by mlantz** [comment]
Thanks @fishmad :) Sometimes in this package I cannot make too many assumptions - where I decide not too I try and leave instructions. Let me know if you guys encounter stuff thats unclear. Thanks :)
