### ISSUE TITLE
Notifications Docs need updated.

### ISSUE THREAD

**Issue by MatthewSH** [YABhq/Laracogs#28]
[These docs](https://laracogs.com/docs/Kits/notifications/) could use some updating to include the steps that are listed in the console output after running `php artisan laracogs:notifications`. I don't have the steps on me a the moment because I don't have the project open; if needed I can get it.

**Comment by mlantz** [comment]
If there are specific parts that would be helpful. I'll do some review of the docs and see what I missed. Thanks.
