### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by matevisky** [YABhq/Laracogs#3]
Hi Team,

The installiation documentation is broken this step should come before the publish command:
php artisan vendor:publish --provider="Yab\Laracogs\LaracogsProvider"

**Comment by mlantz** [comment]
I've updated the readme, does that make more sense?

**Comment by matevisky** [comment]
Thx, Make more sense... I will test it again, I am pretty sure, I am doing something wrong, but I was not able to make it work yet:) Specially from design perspective, the necessery steps are missing out. (npm install, gulp... when to gulp what etc...) But I will make the install process once again, and see where it fails, because I really would like to make it work:)
