### ISSUE TITLE
Validation Errors Display

### ISSUE THREAD

**Issue by Mezzair** [YABhq/Laracogs#31]
After defining the rules in the `Repository/{Model Name}/{Model Name}.php`, the page just seems to refresh and not display the error or session information. The layout is including the `/partials/message.blade.php` and `/partial/error.blade.php`

Any ideas?

**Comment by mlantz** [comment]
Check the routes and see if the routes are loading the web middleware twice, I just recently pulled the web middleware from the builders etc.

**Comment by Mezzair** [comment]
I can verify this. All working now. Thanks.
