### ISSUE TITLE
Update User Error

### ISSUE THREAD

**Issue by bretto36** [YABhq/Laracogs#33]
When updated a user (attempting to change role but happens if saving no change) I get an error which is related to the UserRepo - assignRole. It's expecting RoleName not RoleId. 

Not sure if it needs to be changed to store the RoleName in the form, or change the code to get the rolename from the roleid. 

I will do the necessary code changes, just want to know which one i should do?

Line 105 in UserRepository

The phpdocs are also incorrect (order of parameters)
```
/**
     * Assign a role
     *
     * @param  int $userId
     * @param  string $roleName
     * @return boolean
     */
    public function assignRole($roleName, $userId)
    {
```

**Comment by bretto36** [comment]
I have added a pull request for it, and a separate one to update the php docs.

**Comment by mlantz** [comment]
I remember finding this in the Bootstrap edit file. I must have missed it here thanks!
