### ISSUE TITLE
vendor.receipt

### ISSUE THREAD

**Issue by bretto36** [YABhq/Laracogs#37]
In the docs of the Billing kit it has this line 
Notes

You may want to switch the line in the view vendor.receipt to:

<strong>To:</strong> {{ $user->user()->email }}

We do this because rather than bind the billing to the User, we bound it to the UserMeta.

Where is this view?

**Comment by mlantz** [comment]
Yes, this is generated when you do a vendor publish with cashier. And yes this is needed because the billing is bound to the UserMeta not the user.

**Comment by bretto36** [comment]
Ah i didn't run the publish on cashier! Thanks
