### ISSUE TITLE
5.2 & Label Maker

### ISSUE THREAD

**Issue by absalomedia** [YABhq/Laracogs#4]
Getting this on a fairly vanilla install of L5.2.29

`@input_maker_label('Email') @input_maker_create('email', ['type' => 'string'], $user)
@input_maker_label('Name') @input_maker_create('name', ['type' => 'string'], $user)
@input_maker_label('Phone') @input_maker_create('meta[phone]', ['type' => 'string'], $user)
@input_maker_label('I agree to receive marketing information') @input_maker_create('meta[marketing]', ['type' => 'checkbox'], $user)
@input_maker_label('Terms & Conditions') @input_maker_create('meta[terms_and_cond]', ['type' => 'checkbox'], $user)`

I've followed the install sequence to the letter. Any reason the Input Maker is broken?

Also getting a similar effect with the CRUD builder & pregenerated form maker:

`@form_maker_object($random, FormMaker::getTableColumns('random'))`

**Comment by mlantz** [comment]
Is it giving back an error?

**Comment by absalomedia** [comment]
Not firing / rendering out the Input Maker or Form Maker from what I've provided. Unless there's some setting that's missing from the documentation that makes them do it?

**Comment by mlantz** [comment]
Is it correctly added to the app config in providers? When Blade doesn't recognize the directive it doesnt do anything. So its not loading the provider I suspect.

**Comment by mlantz** [comment]
Try using the helper or the Facade `input_maker_label('Email')` or `FormMaker::fromTable('users')` see what that does - if they provide errors it may point us in the right direction.

**Comment by absalomedia** [comment]
I'm using the Starter Kit & Bootstrap kits & no errors related to it showing up in either PHP error or Laravel logs.

**Comment by absalomedia** [comment]
It's still happening. Specs are Bitnami 5.6.16 Windows Stack (Server 2008 R2). The blades simply refuse to render down input_maker_label, input_maker_create from the InputMaker & similar calls from FormMaker. No errors get logged. Set up providers & aliases as per documentation.

**Comment by mlantz** [comment]
Do you have the latest version? I have no idea why that wouldnt work. Try digging through the vendor package and see if the Blade directives in the provider are ever called. Maybe there is a deeper Laravel issue happening.

**Comment by absalomedia** [comment]
I'm running L5.2.36 with Laracogs 1.9.23 & Laravel Collective HTML/Forms 5.2.4.

Blades seem to work, it's just they won't render out the Laracogs Form & Inputs

**Comment by mlantz** [comment]
Look at the rendered blade templates and see what is in there the blade directives are supposed to just insert in the FormMaker::method etc. I'd like to see what they are generating instead if anything at all.

**Comment by vool** [comment]
hey Just to let you know I just can across the same issue on a clean Larvel install (not stater).

Laravel 5.3.22
form maker 1.0.7
PHP 7.0.8

**Comment by vool** [comment]
a ha 

``php artisan view:clear`` :)
