### ISSUE TITLE
5.2 php artisan laracogs:starter

### ISSUE THREAD

**Issue by DeeJaVu** [YABhq/Laracogs#5]
so i ran php artisan laracogs:starter and migrated and seeded, then when i want to create a new user, i get this error

```
Exception in UserService.php line 82:
We were unable to generate your profile, please try again later.
```

i readed the docs but what im a missing ?

**Comment by mlantz** [comment]
You need to set the email config to log unless you have email set up on your environment.

**Comment by DeeJaVu** [comment]
Ok thanks
