### ISSUE TITLE
Demo or Screenshot

### ISSUE THREAD

**Issue by tillkruss** [YABhq/Laracogs#53]
Is there a demo somewhere, or a video tour, or at least screenshots?

**Comment by mlantz** [comment]
The starter kit (using bootstrap) has screenshots available on https://laracogs.com/docs/ Without the bootstrap option its very plain HTML. The purpose of this is to allow developers to have full control of what their app looks like. Laracogs' kits are generally intended as start points with lots of logic etc handled for you, so the kits plus the CRUD and form builder take tedious tasks out of the equation. Letting you focus on making your app awesome, and as custom a feel as you desire. :)
