### ISSUE TITLE
Is there a support for Braintree billing?

### ISSUE THREAD

**Issue by ergonomicus** [YABhq/Laracogs#54]
The readme and docs don't mention Braintree. Is it supported? What would be needed to implement that?

**Comment by mlantz** [comment]
Technically out of the box I'm not too sure. I've never used it. I would think you would have to switch it in composer, and the database details and just try and see where it fails. I would think they're roughly compatible, at least in the basic sense. The billing kit is rather simple and just sets up basic stuff for subscriptions and single purchases. The BillingService which handles all the other stuff should be compatible as well. If you're up for it I'd give it a shot, and offer PRs for anything that isn't out of the box compatible. Thanks.
