### ISSUE TITLE
Artisan crud command not working

### ISSUE THREAD

**Issue by unbolt** [YABhq/Laracogs#6]
Attempting to use the crud command:

`$ php artisan laracogs:crud news`

or

`$ php artisan laracogs:crud news --migration`

Both return the following:

>   [ErrorException]                            
  array_merge(): Argument #2 is not an array

**Comment by mlantz** [comment]
did you publish the config?

**Comment by unbolt** [comment]
I had not. Publishing it resolved the issue. I didn't see anything about that in the documentation, did I miss it? If not, might be worth adding it.

**Comment by mlantz** [comment]
It should be the first three things on the read me to run composer require, add the provider, and then publish - I'm modifying it so that in case someone misses the publish it will still run :) thanks for the post
