### ISSUE TITLE
Starter Kit / Bootstrap Routing

### ISSUE THREAD

**Issue by absalomedia** [YABhq/Laracogs#7]
Just noted on L5.2.29 that the standard Starter Kit / Bootstrap isn't displaying error messages on the login sequence. This issue also affects the GET/POST responses inside the CRUD generator as well.

Steps to replicate (using Debugbar on vanilla L5.2 install to interrogate issue):

- Install Laracogs
- Install Starter Kit
- Install Bootstrap
- Create a user once migrations are done
- Try to create another user with same name / email
- POST response contains errors / Errorbag reponse with HTTP 302 response
- Page ends up at GET based register page (HTTP 200). No errors are seen as they were part of the 302 response.

**Comment by absalomedia** [comment]
Looks to be related to L5.2.27 & above routing everything through the 'web' middleware

[http://stackoverflow.com/questions/36377420/errorbag-is-always-empty-in-laravel-5-2](http://stackoverflow.com/questions/36377420/errorbag-is-always-empty-in-laravel-5-2)

**Comment by mlantz** [comment]
Did removing it resolve the issue? as per the comment in the thread?

**Comment by absalomedia** [comment]
Yes it did.
