### ISSUE TITLE
Class `Yab\Laracogs\Encryption\LaracogsEncrypter` not found in `LaravelCrypto.php`

### ISSUE THREAD

**Issue by arturmamedov** [YABhq/Laracogs#71]
I installed Laracogs starter, bootstrap and notifications, follow the doc in all steps and when i try to add new Notification i get this error:
```
FatalErrorException in LaravelCrypto.php line 9: 
Class 'Yab\Laracogs\Encryption\LaracogsEncrypter' not found
```

I checked the package is present and have the right namespace `namespace Yab\Laracogs\Encryption;` but the file that contain class `LaracogsEncrypter` is not present anywhere.

What i can do? What hapenned?

```
i'm on windows 10
php 5.6.12
laravel 5.2.41
laracogs v1.9.37
```

**Comment by arturmamedov** [comment]
I try to add this files/class `LaracogsEncrypter.php` , `LaracogsEncrypterInterface.php` in same path from previous version, but it continue to tell me `Not found` :sob:

**Comment by mlantz** [comment]
Blast, its an issue in the crypto package, give me like 10 min, then run composer update, sorry

**Comment by arturmamedov** [comment]
@mlantz work perfectly now! Thank you very much!
