### ISSUE TITLE
Wrong named route, request and redirect('route.name') are generated

### ISSUE THREAD

**Issue by arturmamedov** [YABhq/Laracogs#72]
after run the comand for generate CRUD:
```
php artisan crudmaker:new PriceList_Service --api --ui=bootstrap --migration --schema="id:increments,slug:string,name:string,description:text,active:tinyInteger" --withFacade
```
and acessing the page `/pricelist/services/` i have the error:
````
ErrorException in UrlGenerator.php line 314: Route [pricelist.services.search] not defined. (View: D:\serverpath\dev2016\yabhq-laracogs\www\laracogs\resources\views\pricelist\services\index.blade.php)
```
and
```
InvalidArgumentException in UrlGenerator.php line 314: Route [pricelist.services.search] not defined.
```

In `routes.php` i have this code:
```php
Route::group(['namespace' => 'PriceList', 'prefix' => 'pricelist', 'middleware' => ['web']], function () { 

/*
|--------------------------------------------------------------------------
| Service Routes
|--------------------------------------------------------------------------
*/

Route::resource('services', 'ServiceController', ['except' => ['show']]);
Route::post('services/search', [
    'as' => 'services.search',
    'uses' => 'ServiceController@search'
]);

});
```
and if i change the route name `services.search` in `pricelist.services.search` it work:
```php
Route::post('services/search', [
    'as' => 'pricelist.services.search',
    'uses' => 'ServiceController@search'
]);
```

It's a Laravel error or from Laracogs? My solution go well or i need doing something else for get right?

**Comment by arturmamedov** [comment]
It for `Snake Name` CRUD and another thing is that the Requests file are not generated

**Comment by arturmamedov** [comment]
On `Controller@store` application try to to redirect on wrong named route:
```php
if ($result) {
	return redirect(route('pricelist/services.edit', ['id' => $result->id]))->with('message', 'Successfully created');
}

return redirect(route('pricelist/services.index'))->with('message', 'Failed to create');
```

when the right redirect look like:

```php
if ($result) {
	return redirect(route('pricelist.services.edit', ['id' => $result->id]))->with('message', 'Successfully created');
}

return redirect(route('pricelist.services.index'))->with('message', 'Failed to create');
```

i think `route('pricelist.services.index')` instead of `route('pricelist/services.index')` and its are for all redirects in the Controller

**Comment by mlantz** [comment]
I found the issues with the templates and have updated will do a release tonight. There may have been a typo preventing the request from being made. That will also get pushed.

**Comment by mlantz** [comment]
Please do a composer update. Then you will need to do a vendor publish with force, commit any of your changes before you do that so you dont overwrite any changes you've made.

**Comment by arturmamedov** [comment]
Nothing changed for route names in `route.php` and in `Controller`.

#### in route.php
```php
// seems that Route::post() not get the prefix from Route::group()
Route::post('pricelists/search', [
	'as' => 'pricelists.search', // here for work i ned to add "pricelist." 
	'uses' => 'PricelistController@search'
]);
```

#### in Controller
```php
....
return redirect(route('pricelist/pricelists.index'))...
....
// instead of
return redirect(route('pricelist.pricelists.index'))...
```

And its for generating from `--schema""` and from `existing table`

**Comment by arturmamedov** [comment]
You think it my mistake? I run composer update and something change but not for all things. Maybe i do something wrong? You tested the thing? I can run a fresh new install and try again if yu confirm me that all work now.

**Comment by casperboone** [comment]
Have you (re)published the templates? 

If you already had them in `resources/crudmaker`, you are still using the old templates without the fix to your problem ;).

**Comment by arturmamedov** [comment]
i run `php artisan vendor:publish --provider="Yab\Laracogs\LaracogsProvider"`.
I need to do something manually? in which folder?

**Comment by arturmamedov** [comment]
Ok! I'm sorry for dumb things (i thing run artisan publish was enough), but i need to do it manually, now i see the changes! 
I publish manually all crudmaker files!

Thank again! Hppy coding!
