### ISSUE TITLE
Example for use {--relationships}?

### ISSUE THREAD

**Issue by arturmamedov** [YABhq/Laracogs#74]
Where i can find a doc about `--relationships` command option?
in example with **belongsToMany** or **hasManyThrough**, and can i create multiple relationships when i run `crudmaker:new`?

**Comment by mlantz** [comment]
Docs have been updated

**Comment by MatheusRV** [comment]
I think docs need more exemplo of relationship, i need come here to understand how it works. where can I edit to make a pull request?

**Comment by mlantz** [comment]
https://github.com/GrafiteInc/Docs/blob/master/markdown/others/crud.md

**Comment by mlantz** [comment]
I unified all the package docs into one repo, makes it easier for deployments etc
