### ISSUE TITLE
Better errors when saving with validation fails

### ISSUE THREAD

**Issue by Punksolid** [YABhq/Laracogs#75]
When validation rules are specified if an error happens when saving model the error exception shows a general HttpResponseException without any other explanation. Then after deleting some parts of the model showed me the correct error when I commented the Model::$rules

ways to replicate
1) Specify validation rules in a model,
2a) put Model Events of a class not found
OR
2b) Send a null value to a not null field in database

**Comment by mlantz** [comment]
Is this in relation to the starter kit? or something else? The purpose of the starter kit is to provide a base point in which to build from. We're always open to pull-requests that can help improve the code.

**Comment by Punksolid** [comment]
I think it is related to the CRUD maker maybe, where does the validations are made? I'm trying to figure it out

Thanks

**Comment by Punksolid** [comment]
I found it, It happens a conflict when whoops is enabled filp/whoops, I don't know why this happen but it is not a laracogs error
