### ISSUE TITLE
Does Laracogs play well with Laravel 5.3.6?

### ISSUE THREAD

**Issue by ashbeats** [YABhq/Laracogs#78]
Having some problems getting the crud to work - the routes are not detected. So before I go down a rabbit hole debugging that, figured I'll check with you first. 

What version of laravel has this been tested on?  I tried it on 5.3.6.

**Comment by mlantz** [comment]
What do you mean the routes are not detected and what problems are you having with the crudmaker?

**Comment by Punksolid** [comment]
I was starting upgrading my laravel, Laravel 5.3 has it's routes divided in web. api, and another one, mabe the crud maker searchs for the standard routes.php in laravel 5.2

**Comment by ashbeats** [comment]
The routes were written to \app\Http\routes.php, and on inspection, the file was missing the opening <?php tag.

**Comment by mlantz** [comment]
Which version of the crudmaker is being used?

**Comment by mlantz** [comment]
Also if you've been updating, or using an old config from the crudmaker you can correct it in the config, and set the routes to the new location. The crudmaker should publish the latest if you have the latest, and based on the latest releases it should be correct :) https://github.com/YABhq/CrudMaker/blob/develop/config/crudmaker.php

**Comment by mlantz** [comment]
Are we able to close this with the information given or is this still an issue?

**Comment by ashbeats** [comment]
I can't be certain if that was the cause, because this was a fresh install according to the docs. 

Running (composer require "yab/laracogs") pulled in the following:

$ composer show | grep "yab/"
yab/crudmaker                         v1.1.0 An incredibly powerful and so...
yab/crypto                            v1.0.4 Cryptography tools for Larave...
yab/formmaker                         v1.0.4 A remarkably magical form and...
yab/laracogs                          v2.1.1 Prepare your Laravel apps inc...

Are these the correct versions?

**Comment by ashbeats** [comment]
config/crudmaker.php is showing the correct routes, but they are not being detected. 

However, I got it to work by replacing the old _path_routes_ and _path_api_routes_ key's in:
https://github.com/YABhq/CrudMaker/blob/develop/src/Services/ConfigService.php. 

To:
'_path_routes_'              => $basePath.'/routes/web.php',
'_path_api_routes_'          => $basePath.'/routes/api.php',

**Comment by mlantz** [comment]
hmmm, yes the versions are all good. The config should be detected and used instead of those, those are backup if the config isn't found. Is `crudmaker.php` in your config directory?

**Comment by ashbeats** [comment]
It's working. the config file was not published. I had to manually copy it.
