### ISSUE TITLE
Crud maker with relationships problem

### ISSUE THREAD

**Issue by Germanaz0** [YABhq/Laracogs#79]
I have a laravel running the version of it is **Laravel Framework version 5.3.6** and I have laracogs at his version **2.1.1**.

After running the command:

> php artisan crudmaker:new posts --api --ui=bootstrap --migration --schema="id:increments,name:string,body:text,startdate:date,owner_id:integer|unsigned" --relationships="hasOne|\App\Models\User|owner"

I noticed the following: 

1. The relationship was not done on migration, I had to add "owner_id" on schema command and later on modify the migration table to add the relationship.
2. Form has no relationship, just the id field.

I do not know if this is normal or not, but I suppose that is not, because on the documentation there is the following description:

> This will add in the relationships to your models, as well as add the needed name_id field to your tables. Just one more thing you don't have to worry about.

**Comment by mlantz** [comment]
There may be an oversight in there. Give me a day or two to review and test again. Sorry for the inconvenience. Thanks for posting an issue.

**Comment by mlantz** [comment]
What do you mean by 'modify the migration table to add the relationship.'

**Comment by Germanaz0** [comment]
@mlantz sorry, I had to modify the migration schema file in order to achieve that, it was a typo

**Comment by mlantz** [comment]
Hey so it turns out there is a bug with adding the `owner_id` to the table for the migration. Now the form generator wont work out of the box, you would have to update the form to look more like the forms in the user profiles with roles. It shows how the FormMaker can create the relationships but alas it cant do it without the extra config. thanks

**Comment by maxsilva** [comment]
Hi, About that issue, there is the bug yet. Please, what can I do?

**Comment by maxsilva** [comment]
this: "This will add in the relationships to your models, as well as add the needed name_id field to your tables. Just one more thing you don't have to worry about." don´t work!

**Comment by Artistan** [comment]
so there is no auto form building for relationships, bummer.

**Comment by mlantz** [comment]
```@input_maker_create('roles', [
    'type' => 'relationship',
    'model' => 'App\Repositories\Role\Role',
    'label' => 'label',
    'value' => 'name'
], $user)```

https://docs.grafite.ca/others/input_maker/

**Comment by Artistan** [comment]
Ya, i did that. My statement is that it did not recognize the relation and make the input type=relationship, it was just a text field so i had to go back and create the inputs per relation after the initial creation of the forms.

**Comment by mlantz** [comment]
Hmmm, it should have made a select statement
