### ISSUE TITLE
Delete user does not remove their team-user table entries

### ISSUE THREAD

**Issue by ChrisHe** [YABhq/Laracogs#8]
Using basic Laravel 5.2 with laracogs 1.9.3 and "starter".

Add a new user and invite to one (or more) teams. Then delete the user.
This correctly removes their entry from user, user_meta tables and role_user tables, but does _not_ remove their entries from the team_user table.

**Comment by ChrisHe** [comment]
Obviously adding the right foreign keys to the pivot tables would achieve this, but as "standard" I would expect it to deal with both the role_user and team_user tables in the same way.

**Comment by mlantz** [comment]
Great catch fix is in the next release - thanks :)
