### ISSUE TITLE
Instructions mismatch

### ISSUE THREAD

**Issue by morrismukiri** [YABhq/Laracogs#80]
After running `php artisan laracogs:starter` I get
```sh
Update the model in: config/auth.php, database/factory/ModelFactory.php


App\Repositories\User\User::class


Build something worth sharing!

Don't forget to run:
composer dump
Then:
artisan migrate
```
while the docs say:
Update the App\User::class in: 'config/auth.php' and 'database/factory/ModelFactory.php' to this:

App\Models\User::class

The generator uses the docs style.

**Comment by mlantz** [comment]
Thanks for the PR
