### ISSUE TITLE
Is there a way to customize what the crud generator outputs?

### ISSUE THREAD

**Issue by dopyoman** [YABhq/Laracogs#83]
I've just started poking around with this project. I was wondering if I use the crud generator to create the views for a table is the any config options to customize what the view will be like?

For example in my case I have boolean values that I would like to be represented by check boxes. So in the form-maker.php config file I changed  ``` 'boolean'           => 'number', ```  to ``` 'boolean'           => 'checkbox'```, so I was wondering if there was a way to customize the behavior of the crud generator.

**Comment by mlantz** [comment]
Provided you published the templates you can modify the templates to fit your coding style :)

**Comment by dopyoman** [comment]
Sure I get that. but you use a custom blade directive the generate the form inputs ```@form_maker_table()``` I want to know if there is a way to modify it's behavior without having to edit the source

**Comment by mlantz** [comment]
Nope, the only way to do that would be to fork the repo and tweak it as you see fit.
