### ISSUE TITLE
JWT - Class App\Repositories\User\User::class does not exist

### ISSUE THREAD

**Issue by mistre83** [YABhq/Laracogs#86]
Hi,
i've setup Laracogs for my project and i'm already using it.
Now, i would like to create some API (right now, i have used just web routing).

So, i have moved my route in routes/api.php (because is an AJAX call).
When i call this (jquery, with $.ajax POST) i get the error:

`Class App\Repositories\User\User::class does not exist`

I have follow the guide on how setup Laracogs for API (JWT) and i have also changed the class in `'user' => '\App\Repositories\User\User::class',` inside `jwt.php`

**Comment by mlantz** [comment]
Opps seems like my docs are out of date, it needs to be `App\Models\User::class`

**Comment by mistre83** [comment]
Mhhh ok documentation should be updated because Repository no longer exists :)
However... i'm already using the version with repositories... for this i have used `\App\Repositories\User\User::class`

I have this class and the path is ok. I have already do `dump-autoload` but nothing...

**Comment by mlantz** [comment]
ohh I see the issue:` 'user' => '\App\Repositories\User\User::class'` is incorrect PHP you need to do: `user' => \App\Repositories\User\User::class` the `::class` tells PHP to treat the class name as a string on its own but when you wrap it in a string it tells PHP to use the whole class as a string which doesnt work.
