### ISSUE TITLE
No repositories included

### ISSUE THREAD

**Issue by rorossf** [YABhq/Laracogs#87]
Hello,

I'm using the sample command to generate CRUD, 

```
php artisan crudmaker:new Book
--migration
--schema="id:increments,title:string,author:string"
```

However I don't see it generating any repositories files that I read in the docs.

```
app/Repositories/Book/BookRepository.php
app/Repositories/Book/Book.php
```

Is there a specific reason for this?

**Comment by casperboone** [comment]
Hi,
Since 1.1.0, CrudMaker does no longer generate repositories, see https://github.com/YABhq/CrudMaker/blob/develop/changelog.md#v110---2016-09-06. If you still want them, make sure to lock to an older version.

**Comment by mlantz** [comment]
Thanks @casperboone
