### ISSUE TITLE
bootstrap columns offset

### ISSUE THREAD

**Issue by bholub** [YABhq/Laracogs#88]
I'm brand new to laravel and laracogs so I very well may have missed something, but after initiating a brand new laravel project and adding the laracogs starter and bootstrap I have an issue with the layout where the main column is clearing or being pushed under the side column (screenshot attached). Any thoughts?
![laracogs-bootstraplayout](https://cloud.githubusercontent.com/assets/46856/19214760/2901974c-8d40-11e6-9fb1-ee7544f18760.PNG)

**Comment by mlantz** [comment]
did you do the npm install and gulp?

**Comment by bholub** [comment]
Probably forgot a step. I moved on to try Semantic UI and it works great. I just reverted and retried bootstrap and it's working as well now, so I'm sure (as originally suspected) I was just missing something. Sorry about that, and thanks for your response!
