### ISSUE TITLE
Suggest use FindOrFail(), firstOrFail() on models

### ISSUE THREAD

**Issue by ChrisHe** [YABhq/Laracogs#9]
For example, I see that in Role.php
`public static function findByName($name)
    {
        return Role::where('name', $name)->first();
    }
`
Would it be better to use firstOrFail() so that an exception is thrown at this point if the user asks for a non-existent Role name?
Similarly in other methods such as TeamRepository find() method
`public function findByName($name)
    {
        return $this->model->where('name', $name)->first();
    }`
Would it be better to use firstOrFail() ?

Just a suggestion, keep up the good work!
thx

**Comment by mlantz** [comment]
Switched to fail versions in 1.9.12 thanks for the suggestion
