### ISSUE TITLE
CRUD Service update() function seems to be calling Eloquent with the wrong parameters

### ISSUE THREAD

**Issue by JackWH** [YABhq/Laracogs#90]
Hi,

I generated a Laracogs service using the following command:

    php artisan crudmaker:new people --api --ui=bootstrap --withFacade --migration --schema="id:increments,user_id:integer|unsigned,title:string|nullable,first_name:string,last_name:string" --relationships="belongsTo|user|user"

This created the `update()` functions within the controller and service, which look like this:

Controller:

    /**
     * Update the people in storage.
     *
     * @param  \Illuminate\Http\PersonRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PersonRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Successfully updated');
        }

        return back()->with('message', 'Failed to update');
    }

Service:

    /**
     * Model update.
     *
     * @param  int $id
     * @param  array $input
     * @return bool
     */
    public function update($id, $input)
    {
        return $this->model->update($id, $input);
    }

All good so far... If I do a `dd($id, $input)` in the service `update()` function, before calling `$this->model->update($id, $input)` I can see the correct database ID and input data - all works well so far.

However - when the `$this->model->update($id, $input)` function is called, it throws the following error from Eloquent:

> Type error: Argument 1 passed to Illuminate\Database\Eloquent\Model::update() must be of the type array, string given, called in /home/vagrant/Sites/laravel/app/Services/PersonService.php on line 107

Line 107 is the call to `$this->model->update($id, $input)`.

Eloquent isn't expecting an `$id` string for a model update call. It's expecting to operate on an already-defined object. I can fix it by rewriting the Service `update()` function as follows:

    public function update($id, $input)
    {
        $person = $this->model->find($id);
        return $person->update($input);
    }

Am I doing something wrong, or is this a Laracogs bug?

**Comment by RaphaelBadia** [comment]
Hi,
I just came across the same error and yes, it is a bug that he fixed here, in the development branch : https://github.com/YABhq/CrudMaker/commit/bfb4290fb39f4dfa8256ea83d48580ac60d35455

Laracogs requires the last version of CrudMaker which is https://github.com/YABhq/CrudMaker/tree/v1.1.1/src as of today, and you can see that the fix is not published here yet. So you're right: it is a laracogs bug !

**Comment by mlantz** [comment]
Just released the updates in CrudMaker. I must have missed that this week thanks for the issue post.
