### ISSUE TITLE
ErrorException on laracogs:docs build

### ISSUE THREAD

**Issue by mindspread** [YABhq/Laracogs#95]
When I try to build the docs microsite I get an No such file or directory error.
This is a Laravel 5.3.19 project on Apache running PHP 7.0.0.

**php artisan laracogs:docs build**

>   [ErrorException]                                                                                                                              
>   copy(/Development/laracogs/vendor/yab/laracogs/src/Console/../Documentation/SiteTemplate/index.html): failed to open stream:
> No such file or directory                                                                                                                        
>

**Comment by mlantz** [comment]
Hey thanks for catching that, I found the bug, looks like I missed some updating a few lines in the documentation generator. I'll push a fix today :)
