### ISSUE TITLE
User email verification

### ISSUE THREAD

**Issue by amirulfirdaus** [YABhq/Laracogs#98]
Thank you for such great starter kit for laravel. Just want to suggest a feature for email verification after registration process. This is considered basic functionality these days. Thanks!

**Comment by mlantz** [comment]
Release with this as a new feature coming tonight. However, it will require a fresh app to start from. The nice part is that to deactivate it, all you need to do is remove the middleware from the routes.

**Comment by amirulfirdaus** [comment]
It's nice to hear this! Thanks a lot!
