### ISSUE TITLE
I'm encountering multiple 'Notifications' issues

### ISSUE THREAD

**Issue by zakkyzebra** [YABhq/Laracogs#99]
1. NotificationService.php Line 132
$this->repo->create($input); should be $this->model->create($input);

2. when you try to edit a notification it returns a MethodNotAllowedHttpException
- changed form method to POST

3. After that getting a reflection error
in the http/controllers/admin/notificationController.php
- add “use App\Http\Requests\NotificationUpdateRequest;”
- in the update method change “NotificationRequest” to “NotificationUpdateRequest”

4. now returning a user_id field required error
- realized in the view the form is defaulting to "all" users (user_id 0) and is disabled. When you submit you get the user_id field required error.

I quit after this error since when looking at the update method it does not appear to be able to handle an "All" user notification like the create method does.

**Comment by mlantz** [comment]
Hey @zakkyzebra I did some review and I found the issues and fixed them up and added a couple little things, sorry about the lack of functionality on this. Fixes will be released later today
